import { useState } from 'react';
import Layout from './components/Layout.jsx';
import DashboardPage    from './pages/DashboardPage.jsx';
import StudentsPage     from './pages/StudentsPage.jsx';
import LessonLogPage    from './pages/LessonLogPage.jsx';
import SettingsPage     from './pages/SettingsPage.jsx';
import UsersPage        from './pages/UsersPage.jsx';
import SchedulePage     from './pages/SchedulePage.jsx';
import LessonsAdminPage from './pages/LessonsAdminPage.jsx';
import ProfilePage      from './pages/ProfilePage.jsx';
import StudentProgressPage from './pages/StudentProgressPage.jsx';

const COPY = {
  en: {
    appTitle: 'Patente Pro', appSubtitle: 'Instructor management', instructor: 'Instructor',
    welcomeTo: 'Welcome to',
    main: 'Main', admin: 'Admin', tools: 'Tools', instructor: 'Students', student: 'Student',
    dashboard: 'Dashboard', students: 'Progress', log: 'Log lesson',
    settings: 'Settings', users: 'Users', availabilityAdmin: 'Availability',
    schedule: 'Schedule', manoeuvres: 'Manoeuvres',
    highways: 'Highways', highway: 'Autostrada', toLabel: 'To', fromLabel: 'From',
    addHighway: 'Add', addHighwayPlaceholder: 'New highway name...',
    search: 'Search student...', newLesson: 'New lesson',
    notificationsNone: 'Notifications: no updates',
    databaseConnected: 'DB connected', databaseMock: 'Mock data',
    overview: 'Overview', overviewSub: 'Wednesday, May 22, 2026 — Instructor: Marco Rossi',
    activeStudents: 'Active students', activeStudentsTrend: '+2 this month',
    lessonsToday: 'Lessons today', completedTwo: '2 completed',
    readyForExam: 'Ready for exam', readyTrend: 'up from 1',
    recentStudents: 'Recent students', all: 'All',
    allStudents: 'All students', myStudents: 'Mine', examReady: 'Exam ready',
    name: 'Name', student: 'Student', teacher: 'Instructor',
    progress: 'Progress', status: 'Status', actions: 'Actions',
    ageYears: 'years', lessons: 'lessons', last: 'Last',
    logAction: '+ Log', ready: 'Ready', inProgress: 'In progress', start: 'Start',
    criticalAreas: 'Critical areas (all students)',
    parallelParking: 'Parallel parking', uTurn: 'U-turn',
    priorityCrossroads: 'Priority at intersections', mirrorControl: 'Mirror checks',
    safeOvertaking: 'Safe overtaking', upcomingLessons: 'Upcoming lessons today',
    completed: 'Completed', now: 'Now', inTwoHours: 'In 2 hours', scheduled: 'Scheduled',
    studentsSub: 'Full profile and lesson history for each student',
    totalLessons: 'Total', pending: 'Pending',
    tipologia: 'TIPOLOGIA', autostradaSection: 'AUTOSTRADA',
    noFeedback: 'No feedback recorded for this lesson',
    selectLesson: 'Select a lesson', noLessonsLogged: 'No logged lessons yet',
    profileDetail: 'Detailed profile', manoeuvreEvaluation: 'Manoeuvre evaluation',
    latestNotes: 'Latest instructor notes',
    hillStart: 'Hill start', overtaking: 'Overtaking', motorway: 'Motorway driving',
    parallelParking2: 'Parallel parking',
    cityGood: 'Excellent city driving', parkingImprove: 'Improve parallel parking',
    priorityDifficulty: 'Difficulty with right of way', vehicleControlNote: 'Good vehicle control',
    firstLesson: 'Positive first lesson', parkingGood: 'Excellent parallel parking',
    motorwaySpeed: 'Slow down on the motorway', hillStartGood: 'Good hill start',
    mirrorsOk: 'Mirrors ok', priorityOk: 'Priority ok', steeringWarn: 'Steering warning',
    priorityWarn: 'Priority warning', clutchOk: 'Clutch ok', brakesOk: 'Brakes ok',
    attitudeOk: 'Attitude ok', parkingOk: 'Parking ok', speedWarn: 'Speed warning',
    logSub: 'Complete the report after each driving session',
    lessonDetails: 'Lesson details', date: 'Date', time: 'Time', event: 'Event', duration: 'Duration (min)',
    routeType: 'Route type', city: 'City', extraUrban: 'Extra-urban',
    highway: 'Motorway', parking: 'Parking', night: 'Night',
    generalRating: 'General rating', instructorNotes: 'Instructor notes',
    notesPlaceholder: 'Example: good city driving, improve mirror checks at roundabouts...',
    saveLesson: 'Save lesson', lessonSaved: 'Lesson saved successfully',
    performedManoeuvres: 'Performed manoeuvres',
    vehicleControlCat: 'Vehicle control', manoeuvresCat: 'Manoeuvres', roadCat: 'Road',
    errors: 'Mistakes made',
    schoolSettings: 'School settings',
    schoolSettingsSub: 'Configure school profile, city routes, maneuvers, and error tags',
    schoolProfile: 'School profile', schoolName: 'School name', cityLabel: 'City',
    themeColor: 'Theme color', logoUpload: 'Logo upload', logoUploadHint: 'Drop logo file',
    routeConfiguration: 'Route configuration',
    requiresSubSelection: 'Requires sub-selection', noSubSelection: 'No sub-selection',
    maneuverCatalog: 'Maneuver catalog', errorTagCatalog: 'Error tag catalog',
    saveSettings: 'Save settings', settingsSaved: 'Settings saved',
    userManagement: 'User management',
    userManagementSub: 'Invite teachers and students, edit contacts, deactivate users',
    inviteTeacher: 'Invite teacher', inviteStudent: 'Invite student',
    teachers: 'Teachers', active: 'Active', invited: 'Invited',
    deactivate: 'Deactivate', edit: 'Edit', inviteSent: 'Invite email queued',
    studentDirectory: 'Student directory',
    availabilityPlanner: 'Teacher availability',
    availabilityPlannerSub: 'Review weekly teaching windows before creating lessons',
    weeklyGrid: 'Weekly grid', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri',
    setAvailability: 'Set availability', availabilitySaved: 'Availability saved',
    lessonSchedule: 'Lesson schedule',
    lessonScheduleSub: 'Create lessons and review the calendar by teacher or student',
    lessonsAdmin: 'Lessons',
    lessonsAdminTitle: 'Lessons & Availability',
    lessonsAdminSub: 'Manage scheduled lessons and teacher availability',
    tabLessons: 'Lessons', tabAvailability: 'Availability',
    addLesson: 'Add lesson', addAvailability: 'Add availability',
    noLessonsAdmin: 'No lessons yet', noAvailabilityAdmin: 'No availability blocks yet',
    newScheduledLesson: 'New scheduled lesson',
    teacherView: 'By teacher', studentView: 'By student',
    pickTeacher: 'Pick teacher', pickStudent: 'Pick student',
    eligibleTeachers: 'Eligible teachers', allTeachers: 'All Teachers', calendarView: 'Calendar view',
    lesson: 'Lesson', month: 'Month', week: 'Week', day: 'Day', agenda: 'Agenda',
    today: 'Today', previous: 'Previous', next: 'Next',
    scheduledLessonSaved: 'Lesson scheduled',
    routeList: 'Routes', subRoutes: 'Sub-routes',
    cityDriving: 'City driving', highwayDriving: 'Highway driving',
    extraUrbanHills: 'Extra-urban hills', parkingPractice: 'Parking practice',
    roundaboutPractice: 'Roundabout practice',
    belt: 'Seat belt', mirrors: 'Mirrors', priority: 'Priority', signs: 'Road signs',
    distances: 'Distances', speed: 'Speed', horn: 'Horn', indicators: 'Indicators',
    brakes: 'Brakes',
    manoeuvresSub: 'Official practical exam checklist — Category B',
    vehicleControl: 'Vehicle control', vehicleControlTitle: 'Vehicle control',
    parkingTitle: 'Parking', roadManoeuvres: 'Road manoeuvres', behaviours: 'Evaluated behaviours',
    base: 'Basic', medium: 'Medium', hard: 'Hard', critical: 'Critical',
    seatMirrors: 'Seat and mirror adjustment', clutchBrake: 'Correct clutch and brake use',
    hillStartBrake: 'Hill start with parking brake', smoothGears: 'Smooth gear changes',
    parallelStreet: 'Parallel parking on street', angleParking: 'Angled parking',
    perpendicularParking: 'Perpendicular parking', tightExit: 'Exit from tight parking space',
    doubleRoadUTurn: 'U-turn on two-way road',
    turns: 'Right and left turns at intersections', slowVehicleOvertake: 'Overtake slow vehicle',
    roundabout: 'Cross a roundabout', systematicMirrors: 'Systematic mirror use',
    signalIndicators: 'Signal with indicators', respectPriority: 'Respect right of way',
    laneKeeping: 'Lane keeping',
    completedStatus: 'Completed', language: 'Language',
    profile: 'Profile',
    progress: 'My Progress',
    progressTitle: 'My Learning Progress',
    progressSub: 'Track your driving lessons and feedback',
    lessonsCompleted: 'Lessons completed',
    generalAverage: 'General average',
    recentFeedback: 'Recent feedback',
    viewAllLessons: 'View all lessons',
    noLessonsYet: 'No lessons completed yet',
    excellent: 'Excellent',
    good: 'Good',
    needsImprovement: 'Needs improvement',
  },
  it: {
    appTitle: 'Patente Pro', appSubtitle: 'Gestione istruttori', instructor: 'Istruttore',
    main: 'Principale', admin: 'Admin', tools: 'Strumenti', instructor: 'Istruttore', student: 'Studente',
    welcomeTo: 'Benvenuto a',
    dashboard: 'Dashboard', students: 'Studenti', log: 'Registra lezione',
    settings: 'Impostazioni', users: 'Utenti', availabilityAdmin: 'Disponibilità',
    schedule: 'Calendario', manoeuvres: 'Manovre',
    highways: 'Autostrade', highway: 'Autostrada', toLabel: 'A', fromLabel: 'Da',
    addHighway: 'Aggiungi', addHighwayPlaceholder: 'Nome nuova autostrada...',
    search: 'Cerca studente...', newLesson: 'Nuova lezione',
    notificationsNone: 'Notifiche: nessun aggiornamento',
    databaseConnected: 'DB connesso', databaseMock: 'Dati mock',
    overview: 'Panoramica', overviewSub: 'Mercoledì 22 maggio 2026 — Istruttore: Marco Rossi',
    activeStudents: 'Studenti attivi', activeStudentsTrend: '+2 questo mese',
    lessonsToday: 'Lezioni oggi', completedTwo: '2 completate',
    readyForExam: 'Pronto per esame', readyTrend: 'da 1',
    recentStudents: 'Studenti recenti', all: 'Tutti',
    allStudents: 'Tutti gli studenti', myStudents: 'Miei', examReady: 'Pronto esame',
    name: 'Nome', student: 'Studente', teacher: 'Istruttore',
    progress: 'Progressi', status: 'Stato', actions: 'Azioni',
    ageYears: 'anni', lessons: 'lezioni', last: 'Ultima',
    logAction: '+ Log', ready: 'Pronto', inProgress: 'In corso', start: 'Inizio',
    criticalAreas: 'Aree critiche (tutti gli studenti)',
    parallelParking: 'Parcheggio parallelo', uTurn: 'Inversione a U',
    priorityCrossroads: 'Precedenza agli incroci', mirrorControl: 'Controllo specchietti',
    safeOvertaking: 'Sorpasso sicuro', upcomingLessons: 'Prossime lezioni oggi',
    completed: 'Completata', now: 'Adesso', inTwoHours: 'Tra 2 ore', scheduled: 'Programmata',
    studentsSub: 'Profilo completo e storico lezioni di ogni studente',
    totalLessons: 'Totale', pending: 'In sospeso',
    tipologia: 'TIPOLOGIA', autostradaSection: 'AUTOSTRADA',
    noFeedback: 'Nessun feedback registrato per questa lezione',
    selectLesson: 'Seleziona una lezione', noLessonsLogged: 'Nessuna lezione registrata',
    profileDetail: 'Profilo dettagliato', manoeuvreEvaluation: 'Valutazione manovre',
    latestNotes: 'Ultime note istruttori',
    hillStart: 'Partenza in salita', overtaking: 'Sorpasso', motorway: 'Guida in autostrada',
    cityGood: 'Ottima guida in città', parkingImprove: 'Migliorare parcheggio parallelo',
    priorityDifficulty: 'Difficoltà con le precedenze', vehicleControlNote: 'Buon controllo del veicolo',
    firstLesson: 'Prima lezione positiva', parkingGood: 'Ottimo parcheggio parallelo',
    motorwaySpeed: 'Rallentare in autostrada', hillStartGood: 'Buona partenza in salita',
    mirrorsOk: 'Specchietti ok', priorityOk: 'Precedenze ok', steeringWarn: 'Sterzata critica',
    priorityWarn: 'Precedenze critiche', clutchOk: 'Frizione ok', brakesOk: 'Freni ok',
    attitudeOk: 'Atteggiamento ok', parkingOk: 'Parcheggio ok', speedWarn: 'Velocità critica',
    logSub: 'Compila il report dopo ogni sessione di guida',
    lessonDetails: 'Dettagli lezione', date: 'Data', time: 'Ora', event: 'Evento', duration: 'Durata (min)',
    routeType: 'Tipo di percorso', city: 'Città', extraUrban: 'Extraurbano',
    highway: 'Autostrada', parking: 'Parcheggio', night: 'Notturno',
    generalRating: 'Valutazione generale', instructorNotes: 'Note istruttore',
    notesPlaceholder: "Es: buona guida in città, da migliorare l'uso degli specchietti alle rotonde...",
    saveLesson: 'Salva lezione', lessonSaved: 'Lezione salvata con successo',
    performedManoeuvres: 'Manovre eseguite',
    vehicleControlCat: 'Controllo veicolo', manoeuvresCat: 'Manovre', roadCat: 'Strada',
    errors: 'Errori commessi',
    schoolSettings: 'Impostazioni scuola',
    schoolSettingsSub: 'Configura profilo scuola, percorsi, manovre e tag errore',
    schoolProfile: 'Profilo scuola', schoolName: 'Nome scuola', cityLabel: 'Città',
    themeColor: 'Colore tema', logoUpload: 'Caricamento logo', logoUploadHint: 'Trascina il logo',
    routeConfiguration: 'Configurazione percorsi',
    requiresSubSelection: 'Richiede sotto-selezione', noSubSelection: 'Nessuna sotto-selezione',
    maneuverCatalog: 'Catalogo manovre', errorTagCatalog: 'Catalogo tag errore',
    saveSettings: 'Salva impostazioni', settingsSaved: 'Impostazioni salvate',
    userManagement: 'Gestione utenti',
    userManagementSub: 'Invita istruttori e studenti, modifica contatti e disattiva utenti',
    inviteTeacher: 'Invita istruttore', inviteStudent: 'Invita studente',
    teachers: 'Istruttori', active: 'Attivo', invited: 'Invitato',
    deactivate: 'Disattiva', edit: 'Modifica', inviteSent: 'Email di invito in coda',
    studentDirectory: 'Elenco studenti',
    availabilityPlanner: 'Disponibilità istruttori',
    availabilityPlannerSub: 'Controlla le fasce settimanali prima di creare lezioni',
    weeklyGrid: 'Griglia settimanale', mon: 'Lun', tue: 'Mar', wed: 'Mer', thu: 'Gio', fri: 'Ven',
    setAvailability: 'Imposta disponibilità', availabilitySaved: 'Disponibilità salvata',
    lessonSchedule: 'Calendario lezioni',
    lessonScheduleSub: 'Crea lezioni e consulta il calendario per istruttore o studente',
    lessonsAdmin: 'Lezioni',
    lessonsAdminTitle: 'Lezioni e Disponibilità',
    lessonsAdminSub: 'Gestisci lezioni programmate e disponibilità insegnanti',
    tabLessons: 'Lezioni', tabAvailability: 'Disponibilità',
    addLesson: 'Aggiungi lezione', addAvailability: 'Aggiungi disponibilità',
    noLessonsAdmin: 'Nessuna lezione', noAvailabilityAdmin: 'Nessuna disponibilità',
    newScheduledLesson: 'Nuova lezione programmata',
    teacherView: 'Per istruttore', studentView: 'Per studente',
    pickTeacher: 'Seleziona istruttore', pickStudent: 'Seleziona studente',
    eligibleTeachers: 'Istruttori disponibili', allTeachers: 'Tutti gli istruttori', calendarView: 'Vista calendario',
    lesson: 'Lezione', month: 'Mese', week: 'Settimana', day: 'Giorno', agenda: 'Agenda',
    today: 'Oggi', previous: 'Precedente', next: 'Successivo',
    scheduledLessonSaved: 'Lezione programmata',
    routeList: 'Percorsi', subRoutes: 'Sotto-percorsi',
    cityDriving: 'Guida in città', highwayDriving: 'Guida in autostrada',
    extraUrbanHills: 'Extraurbano collinare', parkingPractice: 'Pratica parcheggio',
    roundaboutPractice: 'Pratica rotonde',
    belt: 'Cintura', mirrors: 'Specchietti', priority: 'Precedenza', signs: 'Segnaletica',
    distances: 'Distanze', speed: 'Velocità', horn: 'Clacson', indicators: 'Frecce', brakes: 'Freni',
    manoeuvresSub: 'Checklist ufficiale esame pratico — Patente B',
    vehicleControl: 'Controllo veicolo', vehicleControlTitle: 'Controllo del veicolo',
    parkingTitle: 'Parcheggio', roadManoeuvres: 'Manovre stradali', behaviours: 'Comportamenti valutati',
    base: 'Base', medium: 'Medio', hard: 'Difficile', critical: 'Critico',
    seatMirrors: 'Regolazione sedile e specchietti', clutchBrake: 'Uso corretto frizione e freno',
    hillStartBrake: 'Partenza in salita con freno di stazionamento', smoothGears: 'Cambio marce fluido',
    parallelStreet: 'Parcheggio parallelo su strada', angleParking: 'Parcheggio a spina',
    perpendicularParking: 'Parcheggio perpendicolare', tightExit: 'Uscita da parcheggio stretto',
    doubleRoadUTurn: 'Inversione a U su strada a doppio senso',
    turns: 'Svolte a destra e sinistra in incrocio', slowVehicleOvertake: 'Sorpasso di veicolo lento',
    roundabout: 'Attraversamento di rotatoria', systematicMirrors: 'Uso sistematico degli specchietti',
    signalIndicators: 'Segnalazione con le frecce', respectPriority: 'Rispetto della precedenza',
    laneKeeping: 'Mantenimento corsia',
    completedStatus: 'Completato', language: 'Lingua',
    profile: 'Profilo',
    progress: 'I miei Progressi',
    progressTitle: 'I miei progressi',
    progressSub: 'Monitora le tue lezioni e i feedback',
    lessonsCompleted: 'Lezioni completate',
    generalAverage: 'Media generale',
    recentFeedback: 'Feedback recenti',
    viewAllLessons: 'Vedi tutte le lezioni',
    noLessonsYet: 'Nessuna lezione completata',
    excellent: 'Eccellente',
    good: 'Buono',
    needsImprovement: 'Da migliorare',
  },
};

export default function App() {
  const [page,  setPage]  = useState('dashboard');
  const [lang,  setLang]  = useState('en');
  const [toast, setToast] = useState('');
  const t = COPY[lang];

  const showToast = (message) => {
    setToast(message);
    window.clearTimeout(showToast._timer);
    showToast._timer = window.setTimeout(() => setToast(''), 2500);
  };

  const navigate = (nextPage) => setPage(nextPage);

  const pageProps = { navigate, showToast, t, lang };

  return (
    <Layout page={page} navigate={navigate} lang={lang} setLang={setLang} showToast={showToast} toast={toast} t={t}>
      {page === 'students'          && <StudentsPage     {...pageProps} />}
      {page === 'log'                && <LessonLogPage    {...pageProps} />}
      {page === 'settings'           && <SettingsPage     {...pageProps} />}
      {page === 'users'              && <UsersPage        {...pageProps} />}
      {page === 'schedule'           && <SchedulePage     {...pageProps} />}
      {page === 'lessonsAdmin'       && <LessonsAdminPage {...pageProps} />}
      {page === 'profile'            && <ProfilePage      {...pageProps} />}
      {page === 'progress'           && <StudentProgressPage {...pageProps} />}
      {page === 'student_progress'    && <StudentProgressPage {...pageProps} />}
      {!['students','log','settings','users','schedule','lessonsAdmin','profile','progress','student_progress'].includes(page) && (
        <DashboardPage {...pageProps} />
      )}
    </Layout>
  );
}